package capability

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// ApprovalString is the serialized form of the approval floor, so generated
// artifacts can state it without knowing Go types.
func (a Approval) ApprovalString() string {
	switch a {
	case ApprovalAlways:
		return "always"
	case ApprovalNever:
		return "never"
	default:
		return "inherited"
	}
}

// CatalogEntry is one row of the generated capability catalog. It is the payload
// behind the generated frontend enum, the tool form descriptors, the LLM tool
// schema and the OpenAPI fragment - one manifest, five downstream artifacts.
type CatalogEntry struct {
	ID         string          `json:"id"`
	Name       string          `json:"name"`
	Title      string          `json:"title,omitempty"`
	Class      Class           `json:"class"`
	Runtime    Runtime         `json:"runtime"`
	Permission string          `json:"permission,omitempty"`
	Approval   string          `json:"approval"`
	Grants     []string        `json:"grants,omitempty"`
	Evidence   bool            `json:"evidence,omitempty"`
	Source     string          `json:"source"`
	Params     json.RawMessage `json:"paramsSchema,omitempty"`
}

// Catalog snapshots the registry in identity order.
func (r *Registry) Catalog() []CatalogEntry {
	specs := r.Specs()
	out := make([]CatalogEntry, 0, len(specs))
	for _, s := range specs {
		grants := make([]string, 0, len(s.Grants))
		for _, g := range s.Grants {
			grants = append(grants, g.String())
		}
		sort.Strings(grants)
		entry := CatalogEntry{
			ID: s.ID, Name: s.Name, Title: s.Title, Class: s.Class, Runtime: s.Runtime,
			Permission: s.Permission, Approval: s.Approval.ApprovalString(),
			Grants: grants, Evidence: s.Evidence, Source: s.sourceLabel(), Params: s.ParamsSchema,
		}
		out = append(out, entry)
	}
	return out
}

func (s *Spec) sourceLabel() string {
	if s.Builtin {
		return "builtin"
	}
	if s.Source == "" {
		return string(s.Runtime)
	}
	return s.Source
}

// MarshalCatalog renders the catalog as deterministic JSON. Determinism matters:
// the drift test compares bytes, and a noisy generator would fail on no change.
func MarshalCatalog(entries []CatalogEntry) ([]byte, error) {
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// RenderCatalogJS wraps the catalog in the global the static pages read, so the
// 241 hand-written tool-name literals in the frontend can be replaced by lookups
// against one generated table.
func RenderCatalogJS(entries []CatalogEntry) ([]byte, error) {
	data, err := MarshalCatalog(entries)
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name)
	}
	list, err := json.Marshal(names)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by ./internal/capability/gen. DO NOT EDIT.\n")
	buf.WriteString("// Source of truth: internal/capability policy table + tools/*.yaml capability blocks.\n")
	buf.WriteString("window.CSAI = window.CSAI || {};\n")
	buf.WriteString("window.CSAI.capabilities = ")
	buf.Write(data)
	buf.WriteString(";\n")
	buf.WriteString("window.CSAI.capabilityNames = ")
	buf.Write(list)
	buf.WriteString(";\n")
	buf.WriteString("window.CSAI.capabilityByName = function (name) {\n")
	buf.WriteString("  var list = window.CSAI.capabilities || [];\n")
	buf.WriteString("  for (var i = 0; i < list.length; i++) { if (list[i].name === name) return list[i]; }\n")
	buf.WriteString("  return null;\n")
	buf.WriteString("};\n")
	return buf.Bytes(), nil
}

// RenderCatalogMarkdown emits the human-reviewable inventory the review pipeline
// needs: identity, class, permission, approval floor and declared grants.
func RenderCatalogMarkdown(entries []CatalogEntry) []byte {
	var buf bytes.Buffer
	buf.WriteString("# 能力目录（生成物，请勿手工编辑）\n\n")
	buf.WriteString("来源：`internal/capability` 策略表 + `tools/*.yaml` 的 `capability:` 清单。\n")
	buf.WriteString("重新生成：`make generate`。不一致时 `TestGeneratedCatalogIsUpToDate` 会失败。\n\n")
	buf.WriteString("| 身份 ID | 工具名 | 级别 | 运行时 | 权限 | 审批 | 声明能力（上限） |\n|---|---|---|---|---|---|---|\n")
	for _, e := range entries {
		buf.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s | %s | %s | %s |\n",
			e.ID, e.Name, e.Class, e.Runtime, orDash(e.Permission), e.Approval, orDash(strings.Join(e.Grants, ", "))))
	}
	return buf.Bytes()
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
