package handler

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"

	"cyberstrike-ai/internal/sse"
)

// The SSE contract gates. Truth source for "what the server emits" is an AST scan of
// the emitter package (internal/sse.Scan), not the registry it is compared with, so
// the two sides of this test can disagree and one of them will be wrong.

// sseGoldenPath is committed next to the extractor that produces it, so the generator
// and the gate read the same file.
const sseGoldenPath = "internal/sse/testdata/sse-kinds.golden.json"

type sseGolden struct {
	Agent    []string `json:"agent"`
	Terminal []string `json:"terminal"`
	// Persisted is the process_details universe; Consumed/Detail/Categories are the page's
	// three tiers. All of it is generated by the same command that writes the JS enum.
	Persisted  []string `json:"persisted"`
	Consumed   []string `json:"consumed"`
	Detail     []string `json:"detailConsumed"`
	Categories []string `json:"c2Consumed"`
}

func moduleRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("no go.mod above the test working directory")
		}
		dir = parent
	}
}

// scanInventory runs the contract extractor (emitter value graph plus the progress-callback
// conduit) against the real tree, so a gate failure points at code rather than at a stale
// list. It calls the same entry point as `make generate`: a gate reading a narrower tree
// than the generator would certify a contract the catalogue never claimed.
func scanInventory(t *testing.T) sse.Inventory {
	t.Helper()
	inv, err := sse.BuildInventory(moduleRoot(t))
	if err != nil {
		t.Fatalf("sse inventory: %v", err)
	}
	return inv
}

func readSSEGolden(t *testing.T) sseGolden {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(moduleRoot(t), sseGoldenPath))
	if err != nil {
		t.Fatalf("golden inventory missing (regenerate with `go run ./internal/sse/gen -root .`): %v", err)
	}
	var golden sseGolden
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatalf("decode golden inventory: %v", err)
	}
	if len(golden.Agent) == 0 || len(golden.Terminal) == 0 {
		t.Fatalf("golden inventory is empty: %+v", golden)
	}
	return golden
}

// handwrittenSSEFrameBaseline was measured at 13 when this gate landed. Every emitter
// has since moved onto internal/sse - the two agent streams, the three bus mirrors,
// the heartbeat, and the C2 event stream - so the gate is now a hard zero: a frame is
// assembled in exactly one place, and any new hand-built one is a regression rather
// than a tolerated straggler. A zero total also makes per-file water marks redundant,
// since one frame anywhere would push the count past the baseline.
const handwrittenSSEFrameBaseline = 0

func TestSSEInventoryMatchesGolden(t *testing.T) {
	inv := scanInventory(t)
	golden := readSSEGolden(t)

	agent := inv.NamesIn(sse.StreamAgent)
	terminal := inv.NamesIn(sse.StreamTerminal)
	minTotal, minAgent, wantTerminal := sse.InventoryFloors()
	if len(inv.Names()) < minTotal || len(agent) < minAgent || len(terminal) != wantTerminal {
		t.Fatalf("inventory traced %d names (%d agent, %d terminal); floors are %d/%d/%d - the extractor is broken",
			len(inv.Names()), len(agent), len(terminal), minTotal, minAgent, wantTerminal)
	}
	t.Logf("inventory: %d agent, %d terminal", len(agent), len(terminal))

	for _, pair := range []struct {
		what   string
		got    []string
		want   []string
		stream string
	}{
		{"agent", agent, golden.Agent, sse.StreamAgent},
		{"terminal", terminal, golden.Terminal, sse.StreamTerminal},
	} {
		want := map[string]bool{}
		for _, name := range pair.want {
			want[name] = true
		}
		gotSet := map[string]bool{}
		for _, name := range pair.got {
			gotSet[name] = true
			if !want[name] {
				t.Errorf("%s stream emits %q but the committed inventory does not list it - regenerate the golden", pair.what, name)
			}
		}
		for _, name := range pair.want {
			if !gotSet[name] {
				t.Errorf("committed inventory lists %s event %q that no longer reaches the wire", pair.what, name)
			}
		}
	}

	// Probes both ways, one per half of the domain: a name the emitter graph traces, a
	// name only the progress-callback conduit reaches, and one that must not be found at
	// all. Without the conduit probe a rule that silently stopped following callbacks
	// would still leave the test green.
	for _, probe := range []struct {
		key  string
		want bool
	}{
		{"done", true},           // assembled in the emitter package
		{"heartbeat", true},      // the transport's own kind
		{"tool_call", true},      // carried by a progress callback, not by an emitter
		{"workflow_start", true}, // produced outside internal/handler
		{"definitely_not_an_event", false},
	} {
		_, inAgent := indexOf(agent, probe.key)
		_, inTerminal := indexOf(terminal, probe.key)
		if got := inAgent || inTerminal; got != probe.want {
			t.Fatalf("probe %s: present=%v, want %v", probe.key, got, probe.want)
		}
	}
}

func indexOf(list []string, value string) (int, bool) {
	for i, item := range list {
		if item == value {
			return i, true
		}
	}
	return 0, false
}

// TestAgentSSEKindsCoverEveryEmittedEvent is the gate the refactor plan asked for: the
// registry and the code must agree, in both directions. An emitter that invents a
// name fails here before it ships a frame the page cannot handle; a declared kind
// nobody emits is dead contract and fails too.
func TestAgentSSEKindsCoverEveryEmittedEvent(t *testing.T) {
	inv := scanInventory(t)
	emitted := inv.NamesIn(sse.StreamAgent)
	declared := AgentSSEKinds()

	if len(declared) < 61 {
		t.Fatalf("registry declares %d kinds; expected at least 61", len(declared))
	}
	declaredNames := make([]string, 0, len(declared))
	for _, kind := range declared {
		declaredNames = append(declaredNames, kind.Name)
		if strings.TrimSpace(kind.Description) == "" {
			t.Errorf("event %q is declared without a description", kind.Name)
		}
	}
	t.Logf("emitted=%d declared=%d", len(emitted), len(declaredNames))

	declaredSet := map[string]bool{}
	for _, name := range declaredNames {
		declaredSet[name] = true
	}
	for _, name := range emitted {
		if !declaredSet[name] {
			t.Errorf("the stream can emit %q but nothing declares it: the writer will refuse it at runtime (sse.ErrUnregisteredKind). Declare it in internal/handler/sse_kinds.go", name)
		}
	}
	emittedSet := map[string]bool{}
	for _, name := range emitted {
		emittedSet[name] = true
	}
	// The other direction: a declared kind the inventory cannot find is a dead contract,
	// and the page would be left waiting for a frame that no longer exists after a rename.
	// This used to be a weaker "appears somewhere in the emitter package as a string" test
	// because four names arrived through a callback returned by a factory, whose parameter
	// positions the value graph does not follow. The conduit extractor now proves them from
	// their call sites, so the check is exact and no longer accepts a bare literal as
	// evidence of an emitter.
	for _, name := range declaredNames {
		if !emittedSet[name] {
			t.Errorf("event %q is declared but the inventory finds no site that emits it", name)
		}
	}
}

// TestTerminalSSEKindsCoverEveryEmittedEvent does the same for the command stream's
// short-key envelope, which is a separate contract with its own clients.
func TestTerminalSSEKindsCoverEveryEmittedEvent(t *testing.T) {
	inv := scanInventory(t)
	emitted := inv.NamesIn(sse.StreamTerminal)
	declared := map[string]bool{}
	for _, kind := range TerminalSSEKinds() {
		if kind.Name == sse.KindHeartbeat {
			continue // the transport's own kind, not a terminal event
		}
		declared[kind.Name] = true
	}
	if len(emitted) != 3 {
		t.Fatalf("terminal stream emits %d names (%v), want 3", len(emitted), emitted)
	}
	for _, name := range emitted {
		if !declared[name] {
			t.Errorf("terminal stream emits %q but terminalSSE does not declare it", name)
		}
	}
	for name := range declared {
		found := false
		for _, emittedName := range emitted {
			if emittedName == name {
				found = true
			}
		}
		if !found {
			t.Errorf("terminalSSE declares %q that nothing emits", name)
		}
	}
}

// TestHandwrittenSSEFramesRatchet counts places that assemble an SSE frame without
// going through internal/sse. The plan's complaint was several wire formats at once;
// the writer is the only one allowed, and each migration has to lower this number.
func TestHandwrittenSSEFramesRatchet(t *testing.T) {
	count, perFile := countHandwrittenFrames(t)
	if count > handwrittenSSEFrameBaseline {
		keys := sortedKeysOf(perFile)
		t.Fatalf("hand-written SSE frames grew to %d (baseline %d): %v. Emit through internal/sse so the registry and one wire format apply.",
			count, handwrittenSSEFrameBaseline, describe(perFile, keys))
	}

}

// oneFramePrefix is what a hand-assembled frame looks like in source: the literal
// `data: ` prefix. One pattern, no second pass over the same line, so the count is the
// number of places that build a frame rather than the number of regexes that fired.
var oneFramePrefix = regexp.MustCompile(`("data: |\x60data: )`)

func countHandwrittenFrames(t *testing.T) (int, map[string]int) {
	t.Helper()
	files, err := filepath.Glob("*.go")
	if err != nil {
		t.Fatal(err)
	}
	total := 0
	perFile := map[string]int{}
	for _, name := range files {
		if strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(name)
		if err != nil {
			t.Fatal(err)
		}
		hits := 0
		for _, line := range strings.Split(string(data), "\n") {
			trimmed := strings.TrimSpace(line)
			// A doc comment describing the wire format is not a place that builds a
			// frame; counting it would make the number mean something other than
			// "emitters left to migrate".
			if strings.HasPrefix(trimmed, "//") {
				continue
			}
			hits += len(oneFramePrefix.FindAllStringIndex(line, -1))
		}
		if hits == 0 {
			continue
		}
		perFile[name] = hits
		total += hits
	}
	return total, perFile
}

func sortedKeysOf(counts map[string]int) []string {
	keys := make([]string, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func describe(counts map[string]int, keys []string) []string {
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, k+"="+intString(counts[k]))
	}
	return out
}

func intString(v int) string { return strconv.Itoa(v) }
